config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'visitors#index'
  devise_for :users
  resources :users
  
  DynamicRouter.load

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  # Try building a slug based on the following fields in
  # increasing order of specificity.
  def slug_candidates
    [
      :title
    ]
  end

  def self.populate_articles
    Article.populate(1000) do |article|
      article.title = Faker::Book.title
      article.content = Faker::Hipster.paragraphs(1, true)
    end
  end

end

app/models/dynamic_router.rb
class DynamicRouter
  def self.load
    Rails.application.routes.draw do
      Page.all.each do |pg|
        puts "Routing #{pg.slug}"
        get "/#{pg.slug}", :to => "pages#show", defaults: { id: pg.slug }
      end
    end
  end

  def self.reload
    Rails.application.routes_reloader.reload!
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  after_save :reload_routes

  def reload_routes
    DynamicRouter.reload
  end
  
  def slug_candidates
    [
      :template_name
    ]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def show 
    @page = Page.friendly.find(params[:id])
    redirect_to not_found_path unless @page
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def generate_content(page)
    data = case page["type"]
      when "articles"
        Article.find(page["article_ids"])
      else
        "page unavailable"
      end

    # return data
    render :partial => "shareds/articles/#{page["layout"]}", :locals => {:data => data}

  end

end

app/helpers/pages_helper.rb
module PagesHelper

  

end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-dismissible alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
li 
  = link_to "ggg" 

app/views/layouts/application-old.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Trip101'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Trip101'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => 'reload'
    == javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    == javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/masonry/4.1.1/masonry.pkgd.min.js"
    == javascript_include_tag "https://npmcdn.com/imagesloaded@4.1/imagesloaded.pkgd.min.js"

    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? yield(:title) : "Trip 101"

    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tag

  body

    == yield

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/pages/show.html.slim
/ .container
/   .row
/     - unless @page.config.blank?
/       - @page.config["modules"].each do |page|
/         = render :partial => "shareds/#{page['layout']}",:locals => {:page => page}
/         


.row
  .column.large-8
     - unless @page.config.blank?
      - @page.config["modules"].each do |page|
        = render :partial => "shareds/#{page['layout']}",:locals => {:page => page}
        .gap


  .column.large-4
    = render :partial => "shareds/side_bar"

app/views/shareds/_header.html.slim
.block 
  .content.no-padding
    article.post.slide
      = link_to "#" do 
        = image_tag page["main_picture"],:class => "image"
      .info
        .title  = page["title"]

app/views/shareds/_layout_1.html.slim
.block
  .title = page["title"]
  .content
    = generate_content(page)

app/views/shareds/_layout_2.html.slim
ul.medium-block-grid-2.responsive-block-grid
  li
    .block
      .title = page["title"]
      .content
        = generate_content(page)

app/views/shareds/_layout_3.html.slim
.block
  .title = page["title"]
  .content
    = generate_content(page)

app/views/shareds/_layout_4.html.slim
.block
  .title = page["title"]
  .content
    = generate_content(page)
  .footer
    a.button.load-more-button.radius href="#"  Load more

app/views/shareds/_side_bar.html.slim
.block.alt
  .title Categories
  .content.no-padding
    ul.categories-navigation
      li.purple
        a href="#"  Environment
      li.pink
        a href="#"  Fashion
      li.green
        a href="#"  Food
      li.orange
        a href="#"  Lifestyle
      li.cyan
        a href="#"  Music
      li.blue
        a href="#"  Technology

.gap
.block.alt
  .title Featured Posts
  .content.no-padding
    article.post.slide
      a href="#" 
        img.image src="http://demo.mekshq.com/voice/wp-content/uploads/2014/11/voice_47-375x195.jpg" /
      .info
        .title Solar Energy for Mother Earth and Everyday Smiles
        .meta 2 min read
.gap
.block.alt
  .title Advertisement
  .content
    ul.small-block-grid-2.responsive-block-grid
      li
        a href="#" 
          img src="http://placehold.it/500x500" /
      li
        a href="#" 
          img src="http://placehold.it/500x500" /
      li
        a href="#" 
          img src="http://placehold.it/500x500" /
      li
        a href="#" 
          img src="http://placehold.it/500x500" /

app/views/shareds/articles/_layout_1.html.slim
ul.small-block-grid-1.medium-block-grid-2.responsive-block-grid
  - data.each do |article|
    li
      article.post.vertical.large
        = link_to "#", :class => "image" do 
          img src="http://demo.mekshq.com/voice/wp-content/uploads/2014/11/voice_62-375x195.jpg" /
        .info
          ul.categories
            li
              a href="#"  Lifestyle
            li
              a href="#"  Technology

          = link_to  article.title, "#", :class => "title"

          .timestamp = time_ago_in_words(article.updated_at.to_time)
          .summary = article.content

app/views/shareds/articles/_layout_2.html.slim
- data.each_with_index do |article,index|
  - if index == 0
    article.post.vertical.large
      = link_to "#", :class => "image" do
        img src="http://demo.mekshq.com/voice/wp-content/uploads/2014/11/voice_32-375x195.jpg" /
      .info
        ul.categories
          li
            a href="#"  Fashion

        = link_to  article.title, "#", :class => "title"
        .timestamp = time_ago_in_words(article.updated_at.to_time)
        .summary = article.content
  - else
    article.post.horizontal.small
      .row.collapse
        .column.small-5
          = link_to "#", :class => "image" do
            img src="http://demo.mekshq.com/voice/wp-content/uploads/2014/11/voice_27-145x100.jpg" /
        .column.small-7
          .info
            ul.categories
              li
                a href="#"  Food
            = link_to  article.title, "#", :class => "title"

app/views/shareds/articles/_layout_3.html.slim
ul.small-block-grid-2.medium-block-grid-5.responsive-block-grid
  - data.each_with_index do |article,index|
    li
      article.post.vertical.small
        = link_to "#", :class => "image" do
          img src="http://demo.mekshq.com/voice/wp-content/uploads/2014/11/unsplash_52bf2bb8d2dd0_1-1-145x100.jpg" title=("Solar Energy for Mother Earth and Everyday Smiles") /
        .info
          = link_to  article.title, "#", :class => "title"

app/views/shareds/articles/_layout_4.html.slim
ul.small-block-grid-1.responsive-block-grid
  - data.each_with_index do |article,index|
    li
      article.post.horizontal.large
        .row.collapse
          .column.medium-5.large-6
            / a.image href="#" 
            = link_to "#", :class => "image" do
              img src="http://demo.mekshq.com/voice/wp-content/uploads/2014/11/voice_62-375x195.jpg" title=("Travelling With Technology – Some Tips From Master") /
          .column.medium-7.large-6
            .info.small-text-center.medium-text-left
              ul.categories
                li
                  a href="#"  Lifestyle
                li
                  a href="#"  Technology

              = link_to  article.title, "#", :class => "title"
              .timestamp = time_ago_in_words(article.updated_at.to_time)

app/views/shareds/olds/_articles.html.slim
- data.each do |article|
  article.post.vertical.large
    a.image href="/article/how-to-best-enjoy-japan-s-capital-of-tokyo" title=("Tokyo Guide - How to Best Enjoy Japan’s Capital Of Tokyo ") 
      img alt="2" src="//static.trip101.com/paragraph_media/pictures/000/036/017/large/2.jpg?1464685754" /
    .info
      
      = link_to  article.title, "#", :class => "title"
      .summary = article.content
      

app/views/shareds/olds/_header.html.slim
header.business-header style="background-image: url('#{page["main_picture"]}') "
  .container
    .row
      .col-lg-12
        h1.tagline = page["title"]

app/views/shareds/olds/_layout.html.slim
.layout
  .col-sm-6.col-md-6
    .block
      h2.title.purple = page["title"]
      .content
        = generate_content(page)
        article.post.vertical.large
          a.image href="/article/how-to-best-enjoy-japan-s-capital-of-tokyo" title=("Tokyo Guide - How to Best Enjoy Japan’s Capital Of Tokyo ") 
            img alt="2" src="//static.trip101.com/paragraph_media/pictures/000/036/017/large/2.jpg?1464685754" /
          .info
            ul.categories
              li
                a href="/things-to-do/sightseeing" itemprop="genre"  Sightseeing
            a.title href="/article/how-to-best-enjoy-japan-s-capital-of-tokyo" title=("Tokyo Guide - How to Best Enjoy Japan’s Capital Of Tokyo ")  Tokyo Guide - How to Best Enjoy Japan’s Capital Of Tokyo
            .summary Despite the amazing urban environment, Japanese culture and nature can still be found in Tokyo, making it one of the most exciting places in Japan to...

app/views/shareds/olds/_layout_1.html.slim
.layout
  .col-sm-6.col-md-6
    .block
      h2.title.purple = page["title"]
      .content
        = generate_content(page)
        

app/views/shareds/olds/_layout_2.html.slim
.layout_1
  .col-sm-12.col-md-12
    .row
      h1 = page["title"]
      = generate_content(page)

app/views/shareds/olds/_layout_3.html.slim
|layout_3.html.slim

app/views/shareds/olds/_layout_4.html.slim
.layout_1
  .col-sm-12.col-md-12
    .row
      h1 = page["title"]
      = generate_content(page)

app/views/shareds/olds/articles/_layout_1.html.slim
- data.each do |article|
  article.post.vertical.large
    a.image href="/article/how-to-best-enjoy-japan-s-capital-of-tokyo" title=("Tokyo Guide - How to Best Enjoy Japan’s Capital Of Tokyo ") 
      img alt="2" src="//static.trip101.com/paragraph_media/pictures/000/036/017/large/2.jpg?1464685754" /
    .info
      
      = link_to  article.title, "#", :class => "title"
      .summary = article.content
      

app/views/shareds/olds/articles/_layout_2.html.slim
- data.each do |article|
  .col-sm-6.col-md-3
    .thumbnail
      article.post.vertical.large
        a.image href="/article/tokyo-s-top-5-searched-hotels" title=("Tokyo Hotel Guide -  Top 5 Searched Hotels") 
          img alt="2" src="//static.trip101.com/paragraph_media/pictures/000/054/763/large/2.jpg?1470108265" /
        .info
          = link_to  article.title, "#", :class => "title"
          .summary = article.content

app/views/shareds/olds/articles/_layout_4.html.slim
- data.each do |article|
  .col-sm-6.col-md-4
    .thumbnail
      article.post.vertical.large
        a.image href="/article/tokyo-s-top-5-searched-hotels" title=("Tokyo Hotel Guide -  Top 5 Searched Hotels") 
          img alt="2" src="//static.trip101.com/paragraph_media/pictures/000/054/763/large/2.jpg?1470108265" /
        .info
          = link_to  article.title, "#", :class => "title"
          .summary = article.content

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/visitors/index.html.erb
<!-- Image Background Page Header -->
<!-- Note: The background image is set within the business-casual.css file. -->
<!-- <header class="business-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="tagline">Business Name or Tagline</h1>
            </div>
        </div>
    </div>
</header>
 -->
<!-- Page Content -->
<!-- <div class="container">

    <hr>

    <div class="row">
        <div class="col-sm-8">
            <h2>What We Do</h2>
            <p>Introduce the visitor to the business using clear, informative text. Use well-targeted keywords within your sentences to make sure search engines can find the business.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et molestiae similique eligendi reiciendis sunt distinctio odit? Quia, neque, ipsa, adipisci quisquam ullam deserunt accusantium illo iste exercitationem nemo voluptates asperiores.</p>
            <p>
                <a class="btn btn-default btn-lg" href="#">Call to Action &raquo;</a>
            </p>
        </div>
        <div class="col-sm-4">
            <h2>Contact Us</h2>
            <address>
                <strong>Start Bootstrap</strong>
                <br>3481 Melrose Place
                <br>Beverly Hills, CA 90210
                <br>
            </address>
            <address>
                <abbr title="Phone">P:</abbr>(123) 456-7890
                <br>
                <abbr title="Email">E:</abbr> <a href="mailto:#">name@example.com</a>
            </address>
        </div>
    </div> -->
    <!-- /.row -->

   <!--  <hr>

    <div class="row">
        <div class="col-sm-4">
            <img class="img-circle img-responsive img-center" src="http://placehold.it/300x300" alt="">
            <h2>Marketing Box #1</h2>
            <p>These marketing boxes are a great place to put some information. These can contain summaries of what the company does, promotional information, or anything else that is relevant to the company. These will usually be below-the-fold.</p>
        </div>
        <div class="col-sm-4">
            <img class="img-circle img-responsive img-center" src="http://placehold.it/300x300" alt="">
            <h2>Marketing Box #2</h2>
            <p>The images are set to be circular and responsive. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
        </div>
        <div class="col-sm-4">
            <img class="img-circle img-responsive img-center" src="http://placehold.it/300x300" alt="">
            <h2>Marketing Box #3</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
        </div>
    </div> -->
    <!-- /.row -->

    <!-- <hr> -->

    <!-- Footer -->
   <!--  <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Your Website 2014</p>
            </div>
        </div> -->
        <!-- /.row -->
    <!-- </footer> -->

<!-- </div> -->
<!-- /.container -->